---
###############################################################################
# Install Packages & Services
###############################################################################
# Traefik is a static golang binary. Just extract and set proper permissions.

- name: 'Install | Traefik {{ _traefik_srv_version.raw }}'
  when: not _traefik_srv_force_config_only_enable.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.repo'
  vars:
    repo_release_owner: '{{ traefik_role_repo_release_owner }}'
    repo_release_repo: '{{ traefik_role_repo_release_repo }}'
    repo_release_tag: '{{ _traefik_srv_version.raw }}'
    repo_release_specifier: '{{ traefik_role_repo_release_specifier }}'
    repo_release_asset: '{{ traefik_role_repo_release_asset }}'
    repo_extract_dir: '{{ traefik_role_repo_extract_dir }}'
    repo_extract_symlink: '{{ traefik_role_repo_extract_symlink }}'
    repo_extract_delete_old_versions:
      '{{ _traefik_srv_delete_old_versions_enable.raw }}'
    repo_force_overwrite: '{{ _traefik_srv_force_overwrite.raw }}'
    repo_extract_mode: 'a-st'
    repo_extract_extra_opts: []
    repo_extract_remove_files:
      - 'CHANGELOG.md'
      - 'LICENSE.md'
